# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Demo1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import numpy as np
from PyQt5 import QtCore, QtGui, QtWidgets
class project(object):
    def inzialize1darray(array,int):
        array.append(int)
    def intialize2darray(array,int,index):
        array[index].append(int)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 669)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 520, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(530, 520, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 40, 101, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(380, 50, 91, 16))
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(180, 40, 131, 31))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(500, 40, 131, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.max = QtWidgets.QTableWidget(self.centralwidget)
        self.max.setGeometry(QtCore.QRect(40, 110, 211, 191))
        self.max.setObjectName("max")
        self.max.setColumnCount(0)
        self.max.setRowCount(0)
        self.allocation = QtWidgets.QTableWidget(self.centralwidget)
        self.allocation.setGeometry(QtCore.QRect(300, 110, 161, 192))
        self.allocation.setObjectName("allocation")
        self.allocation.setColumnCount(0)
        self.allocation.setRowCount(0)
        self.available = QtWidgets.QTableWidget(self.centralwidget)
        self.available.setGeometry(QtCore.QRect(510, 110, 161, 192))
        self.available.setObjectName("available")
        self.available.setColumnCount(0)
        self.available.setRowCount(0)
        self.need = QtWidgets.QTableWidget(self.centralwidget)
        self.need.setGeometry(QtCore.QRect(40, 320, 211, 161))
        self.need.setObjectName("need")
        self.need.setColumnCount(0)
        self.need.setRowCount(0)
        self.total = QtWidgets.QTableWidget(self.centralwidget)
        self.total.setGeometry(QtCore.QRect(290, 320, 231, 151))
        self.total.setObjectName("total")
        self.total.setColumnCount(0)
        self.total.setRowCount(0)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 90, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(370, 90, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(570, 90, 47, 13))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(120, 300, 47, 13))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(380, 300, 47, 13))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(620, 340, 190, 21))
        self.label_8.setObjectName("label_3")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(620, 430, 190, 81))
        self.label_9.setObjectName("label_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(360, 520, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(790, 250, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(710, 110, 251, 111))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        MainWindow.setCentralWidget(self.centralwidget)

        
        #connect generate button to generate function
        self.pushButton.clicked.connect(self.generate)
        self.pushButton_2.clicked.connect(self.enter) 
        self.pushButton_3.clicked.connect(self.safe)
        self.pushButton_4.clicked.connect(self.newentry)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    #function to generate input tables
    def generate(self):
        #number of resources
        m=int(self.textEdit.toPlainText())
        #number of processes
        n=int(self.textEdit_2.toPlainText())
        #generate max table
        self.max.setColumnCount(m)
        self.max.setRowCount(n)
        for i in range(n):
            for j in range(m):
                self.max.setItem(i,j,QtWidgets.QTableWidgetItem())
        #generate allocation table
        self.allocation.setColumnCount(m)
        self.allocation.setRowCount(n)
        for i in range(n):
            for j in range(m):
                self.allocation.setItem(i,j,QtWidgets.QTableWidgetItem())
        #generate available table
        self.available.setColumnCount(m)
        self.available.setRowCount(1)
        for i in range(m):
            self.available.setItem(0,i,QtWidgets.QTableWidgetItem())
        #generate need table
        self.need.setColumnCount(m)
        self.need.setRowCount(n)
        for i in range(n):
            for j in range(m):
                self.need.setItem(i,j,QtWidgets.QTableWidgetItem())
        #generate safe sequence table
        self.total.setColumnCount(m)
        self.total.setRowCount(1)
        for i in range(m):
            self.total.setItem(0,i,QtWidgets.QTableWidgetItem())
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "generate"))
        self.pushButton_2.setText(_translate("MainWindow", "enter"))
        self.label.setText(_translate("MainWindow", "number of resources"))
        self.label_2.setText(_translate("MainWindow", "number of process"))
        self.label_3.setText(_translate("MainWindow", "max"))
        self.label_4.setText(_translate("MainWindow", "allocation"))
        self.label_5.setText(_translate("MainWindow", "available"))
        self.label_6.setText(_translate("MainWindow", "need"))
        self.label_7.setText(_translate("MainWindow", "total"))
        self.label_8.setText(_translate("MainWindow", ""))
        self.label_9.setText(_translate("MainWindow", ""))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "proc id"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "res id"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "nb of res"))
        self.pushButton_4.setText(_translate("MainWindow", "user entry"))

        self.pushButton_3.setText(_translate("MainWindow", "check"))
    def enter(self):
        #number of resources
        self.n=int(self.textEdit.toPlainText())
        #number of processes
        self.m=int(self.textEdit_2.toPlainText())
        self.maxi=[]
        self.allocationi=[]
        self.availablei=[]
        self.needi=[]
        self.totali=[]
        self.sequencei=[]
        for i in range(self.m):
            self.maxi.append([])
            self.allocationi.append([])
            
            
            for j in range(self.n):
                
                self.maxi[i].append(int(self.max.item(i,j).text()))
                self.allocationi[i].append(int(self.allocation.item(i,j).text()))
        for i in range(self.n):
            self.totali.append(int(self.total.item(0,j).text()))
        print(self.allocationi)


        for i in range(self.m):
            self.needi.append([])
            for j in range(self.n):
                tmp=self.maxi[i][j]-self.allocationi[i][j]
                self.needi[i].append(tmp)

        print(self.needi)


        
        
        xx = np.arange(self.n)
        for j in range(self.n):
            z=0
            for i in range(self.m):
             z=z+self.allocationi[i][j]
             #fill x with z
            xx[j]=z
        
        self.availablei = self.totali - xx  


        for i in range(self.m):
            
            for j in range(self.n):
                self.need.item(i,j).setText(str(self.needi[i][j]))
        for i in range(self.n):
            self.available.item(0,i).setText(str(self.availablei[i]))


    def newentry(self):
         self.newentryi=[]
         for i in range(3):
             self.newentryi.append((int(self.tableWidget.item(i,0).text())))
        
         self.allocationi[self.newentryi[0]][self.newentryi[1]]+=self.newentryi[2]
         self.allocation.item(self.newentryi[0],self.newentryi[1]).setText(str(self.allocationi[self.newentryi[0]][self.newentryi[1]]))


    
        
    def check(self,i):
        for j in range(self.n):
            if(self.needi[i][j]>self.availablei[j]):
                return 0
        return 1    
    #calculate the tables
    def safe(self):
        _translate = QtCore.QCoreApplication.translate
        self.Sequence = np.zeros((self.m,),dtype=int)
        visited = np.zeros((self.m),dtype=int)
        self.count = 0
        while( self.count < self.m ):
            temp=0
            for i in range( self.m ):
                if( visited[i] == 0 ):
                    if(self.check(i)):
                        self.Sequence[self.count]=i
                        self.count+=1
                        visited[i]=1
                        temp=1
                    
            if(temp == 0):
                break


        if(self.count < self.m):
            self.label_8.setText(_translate("MainWindow", "the system is not safe"))
        else:
            self.label_8.setText(_translate("MainWindow", "the system is  safe"))
            self.label_9.setText(_translate("MainWindow", "the safe sequence is"+str(self.Sequence)))
            
        
        
          


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
